version: '3.4'
services:
  share-mv-controls-poc-share:
    image: alfresco-share-share-mv-controls-poc:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../share-mv-controls-poc-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: share-mv-controls-poc-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  share-mv-controls-poc-acs:
    image: alfresco-content-services-share-mv-controls-poc:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../share-mv-controls-poc-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - share-mv-controls-poc-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - share-mv-controls-poc-postgres
  share-mv-controls-poc-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - share-mv-controls-poc-db-volume:/var/lib/postgresql/data
  share-mv-controls-poc-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: share-mv-controls-poc-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: share-mv-controls-poc-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - share-mv-controls-poc-ass-volume:/opt/alfresco-search-services/contentstore
      - share-mv-controls-poc-ass-volume:/opt/alfresco-search-services/data
volumes:
  share-mv-controls-poc-acs-volume:
    external: true
  share-mv-controls-poc-db-volume:
    external: true
  share-mv-controls-poc-ass-volume:
    external: true